In [10]:
# importing all the libraries required here
import pandas as pd
#import matplotlib.pyplot as plt
import numpy as np


In [11]:
# reading the dataset
datasetNames = ['ID number', 'Diagnosis', 
                'Mean Radius', 'Mean Texture', 'Mean Perimeter', 'Mean Area', 'Mean Smoothness', 'Mean Compactness', 'Mean Concavity', 'Mean Concave Points', 'Mean Symmetry', 'Mean Fractal Dimension',
                'SE Radius', 'SE Texture', 'SE Perimeter', 'SE Area', 'SE Smoothness', 'SE Compactness', 'SE Concavity', 'SE Concave Points', 'SE Symmetry', 'SE Fractal Dimension',
                'Worst Radius', 'Worst Texture', 'Worst Perimeter', 'Worst Area', 'Worst Smoothness', 'Worst Compactness', 'Worst Concavity', 'Worst Concave Points', 'Worst Symmetry', 'Worst Fractal Dimension']
dataset = pd.read_csv('data/wdbc.data', names = datasetNames, sep = ',')
dataset.head()

,ID number,Diagnosis,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,...,Worst Radius,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [12]:
dataset = dataset.drop(columns=['ID number'])

m , n = dataset.shape  # m = no. of samples, n = no. of features + target class
m , n
dataset = np.array(dataset)

np.random.shuffle(dataset) # shuffle before splitting into dev and training sets

dataset = dataset[0:400].T
Y_dev = dataset[0]
X_dev = dataset[1:n]
print(Y_dev, X_dev)

['M' 'M' 'M' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B'
 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'B'
 'M' 'M' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'B'
 'M' 'M' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'B'
 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'M'
 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'M' 'M' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'B'
 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'M' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'M

In [13]:
"""# change to numpy array 
dataset = np.array(dataset)

# shuffle each row of the data before sending to train network
np.random.shuffle(dataset)


#sanity check
print(dataset)
"""

'# change to numpy array \ndataset = np.array(dataset)\n\n# shuffle each row of the data before sending to train network\nnp.random.shuffle(dataset)\n\n\n#sanity check\nprint(dataset)\n'

In [14]:
"""print(dataset.shape)

#seperate training and test sets
X_train = dataset[1:,:400] #train network on 400 samples
Y_train = dataset[0,:400]

X_test = dataset[1:,400:m] #test network on the remaining samples
Y_test = dataset[0,400:m]


print(Y_train)
print(X_train)"""

'print(dataset.shape)\n\n#seperate training and test sets\nX_train = dataset[1:,:400] #train network on 400 samples\nY_train = dataset[0,:400]\n\nX_test = dataset[1:,400:m] #test network on the remaining samples\nY_test = dataset[0,400:m]\n\n\nprint(Y_train)\nprint(X_train)'

In [15]:
# Initialise ANN
import ANN
import layer

# categorizing data into numericals, 0 = M, 1 = B
Y_train = pd.factorize(Y_dev)[0]

# testing one hot encoder
Y_train = ANN.one_hot_encode(Y_train, 2)



In [20]:
"""REMOVE BEFORE SUBMISSION"""
import importlib
importlib.reload(ANN)
importlib.reload(layer)

# initialise with learning rate, choice of loss funciton, input vector, output vector
ann = ANN.ANN(0.1,2,X_dev,Y_train)
activations = [2,2,2] # 1-tanh, 2-relu, 3-sigmoid - activations of each layer
ann.setLayers(activations, 7, 2) # variable arguments represent the number of nodes in each non-input layer 


ann.train()
"""
i = 0
for l in ann.layers:
    print("\nProperties of layer", i, ":")
    l.get_properties()
    i += 1
"""


the activations are [2, 2, 2]
the variable argument is  (7, 2)
number of hidden layers 1 

input to the network is [[15.1 11.84 20.92 ... 19.16 13.75 13.05]
 [22.02 18.7 25.09 ... 26.6 23.77 13.84]
 [97.26 77.93 143.0 ... 126.2 88.54 82.71]
 ...
 [0.153 0.1546 0.2542 ... 0.1872 0.06106 0.03532]
 [0.2675 0.4761 0.2929 ... 0.3258 0.2663 0.2107]
 [0.07873 0.1402 0.09873 ... 0.0972 0.06321 0.0658]]
the output is [[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1

ValueError: shapes (30,400) and (30,7) not aligned: 400 (dim 1) != 30 (dim 0)

In [ ]:
importlib.reload(ANN)
importlib.reload(layer)

#for first 2 columns
#print("the output from the network is", ann.test(np.array(X_train)[:,:2]))
print("the output from the network is", ann.test(np.array(X_train)[:,:1].T))
print(Y_train[0])



test input  [[13.56 13.9 88.59 561.3 0.1051 0.1192 0.0786 0.04451 0.1962 0.06303
  0.2569 0.4981 2.011 21.03 0.005851 0.02314 0.02544 0.00836 0.01842
  0.002918 14.98 17.13 101.1 686.6 0.1376 0.2698 0.2577 0.0909 0.3065
  0.08177]]
the output from the network is [array([[1.27976675e-14, 1.00000000e+00]], dtype=float32)]
[1. 0.]


In [ ]:
#print("the output from the network is", ann.test(np.array(X_train)[:,:2]))
print("the output from the network is", ann.test(X_train))
print(Y_train)

test input  [[13.56 13.94 15.53 ... 13.53 10.66 13.0]
 [13.9 13.17 33.56 ... 10.94 15.15 21.82]
 [88.59 90.31 103.7 ... 87.91 67.49 87.5]
 ...
 [0.0909 0.1015 0.2014 ... 0.07407 0.0 0.206]
 [0.3065 0.216 0.3512 ... 0.271 0.271 0.4378]
 [0.08177 0.07253 0.1204 ... 0.07191 0.06164 0.1072]]


ValueError: shapes (30,400) and (30,7) not aligned: 400 (dim 1) != 30 (dim 0)