In [187]:
import numpy as np
import pandas as pd

# Initialise ANN
import NeuralNet
import layer

from sklearn.preprocessing import StandardScaler, MinMaxScaler

datasetNames = ['ID number', 'Diagnosis', 
                'Mean Radius', 'Mean Texture', 'Mean Perimeter', 'Mean Area', 'Mean Smoothness', 'Mean Compactness', 'Mean Concavity', 'Mean Concave Points', 'Mean Symmetry', 'Mean Fractal Dimension',
                'SE Radius', 'SE Texture', 'SE Perimeter', 'SE Area', 'SE Smoothness', 'SE Compactness', 'SE Concavity', 'SE Concave Points', 'SE Symmetry', 'SE Fractal Dimension',
                'Worst Radius', 'Worst Texture', 'Worst Perimeter', 'Worst Area', 'Worst Smoothness', 'Worst Compactness', 'Worst Concavity', 'Worst Concave Points', 'Worst Symmetry', 'Worst Fractal Dimension']

data = pd.read_csv('data/wdbc.data', names = datasetNames, sep = ',')
data = data.replace({'M': 0, 'B':1})
data = data.drop(columns=['ID number'])
data.head()

,Diagnosis,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,Mean Symmetry,...,Worst Radius,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension
0,0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,0,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,0,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,0,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,0,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [188]:
# scaler = MinMaxScaler()
# data = scaler.fit_transform(data)
# print(data)

In [189]:
data = np.array(data)
m, n = data.shape #find number of samples and features in the data

np.random.shuffle(data) #shuffle the data

#seperate the target class from the rest of the dataset
data_train = data[100:m].T
Y_train = data_train[0].astype(int)
X_train = data_train[1:n]
print(X_train)



[[1.300e+01 1.075e+01 8.726e+00 ... 1.160e+01 1.120e+01 1.388e+01]
 [2.513e+01 1.497e+01 1.583e+01 ... 2.449e+01 2.937e+01 1.616e+01]
 [8.261e+01 6.826e+01 5.584e+01 ... 7.423e+01 7.067e+01 8.837e+01]
 ...
 [5.921e-02 3.413e-02 1.050e-01 ... 4.815e-02 0.000e+00 4.537e-02]
 [2.306e-01 2.300e-01 2.926e-01 ... 3.244e-01 1.566e-01 2.542e-01]
 [6.291e-02 6.769e-02 1.017e-01 ... 6.745e-02 5.905e-02 6.623e-02]]


In [190]:
#normalize the data https://www.kaggle.com/code/joshbeau/tumor-diagnosis-neural-net-from-first-principals
X_mean = np.mean(X_train,axis=1,keepdims=True) #Find the mean of each feature
X_max = np.max(X_train,axis=1,keepdims=True) #Find the maximum of each feature
X_normalized = (X_train-X_mean)/(X_max) #Normalizing our dataset by subtracting the mean and dividing by the max

X_train = X_normalized

In [194]:
"""REMOVE BEFORE SUBMISSION"""
import importlib
importlib.reload(NeuralNet)
importlib.reload(layer)


ann = NeuralNet.ANN(0.5,1,X_train,Y_train)
activations = [1,3] # 1-tanh, 2-relu, 3-sigmoid - activations of each layer
ann.setLayers(activations, 14, 2) # variable arguments represent the number of nodes in each non-input layer 

ann.train_sgd()


adding input layer
added 1 hidden layer
added 1 output layer
propogating back
propogating back
Iteration:  0
Accuracy  0.5266524520255863
propogating back
propogating back
Iteration:  1
Accuracy  0.535181236673774
propogating back
propogating back
Iteration:  2
Accuracy  0.5501066098081023
propogating back
propogating back
Iteration:  3
Accuracy  0.5628997867803838
propogating back
propogating back
Iteration:  4
Accuracy  0.5756929637526652
propogating back
propogating back
Iteration:  5
Accuracy  0.5906183368869936
propogating back
propogating back
Iteration:  6
Accuracy  0.6140724946695096
propogating back
propogating back
Iteration:  7
Accuracy  0.6226012793176973
propogating back
propogating back
Iteration:  8
Accuracy  0.6183368869936035
propogating back
propogating back
Iteration:  9
Accuracy  0.6289978678038379
propogating back
propogating back
Iteration:  10
Accuracy  0.6396588486140725
propogating back
propogating back
Iteration:  11
Accuracy  0.6460554371002132
propogating ba

### Observations
Accuracy of 96% observed with learning rate 0.008, 10 nodes in 1 hidden layer, 2 output nodes, 200 epochs, sgd

In [192]:
"""REMOVE BEFORE SUBMISSION"""
import importlib
importlib.reload(NeuralNet)
importlib.reload(layer)
ann_binary = NeuralNet.ANN(0.1,2,X_train,Y_train)
activations = [2,2] # 1-tanh, 2-relu, 3-sigmoid - activations of each layer
ann_binary.setLayers(activations, 14, 1) # variable arguments represent the number of nodes in each non-input
ann_binary.train_sgd()


adding input layer
added 1 hidden layer
added 1 output layer
propogating back
propogating back
Iteration:  0
Accuracy  0.36886993603411516
propogating back
propogating back
Iteration:  1
Accuracy  0.36886993603411516
propogating back
propogating back
Iteration:  2
Accuracy  0.36886993603411516
propogating back
propogating back
Iteration:  3
Accuracy  0.36886993603411516
propogating back
propogating back
Iteration:  4
Accuracy  0.36886993603411516
propogating back
propogating back
Iteration:  5
Accuracy  0.36886993603411516
propogating back
propogating back
Iteration:  6
Accuracy  0.36886993603411516
propogating back
propogating back
Iteration:  7
Accuracy  0.36886993603411516
propogating back
propogating back
Iteration:  8
Accuracy  0.36886993603411516
propogating back
propogating back
Iteration:  9
Accuracy  0.36886993603411516
propogating back
propogating back
Iteration:  10
Accuracy  0.36886993603411516
propogating back
propogating back
Iteration:  11
Accuracy  0.36886993603411516
p